require("config.utils").plugin_setup("nvim-treesitter.configs", {
	ensure_installed = {
		"css",
		"dockerfile",
		"fish",
		"html",
		"http",
		"javascript",
		"json",
		"jsonc",
		"lua",
		"markdown",
		"regex",
		"scss",
		"toml",
		"typescript",
		"vim",
		"yaml",
	},
	highlight = {
		enable = true,
	},
	matchup = {
		enable = true,
	},
	autotag = {
		enable = true,
	},
	textobjects = {
		move = {
			enable = true,
			set_jumps = true,
			goto_next_start = {
				["]f"] = "@function.outer",
				["]b"] = "@parameter.outer",
				["]d"] = "@block.inner",
				["]e"] = "@function.inner",
				["]a"] = "@attribute.inner",
				-- ["]c"] = "@call.inner",
			},
			goto_next_end = {
				["]F"] = "@function.outer",
				["]B"] = "@parameter.outer",
				["]D"] = "@block.inner",
				["]E"] = "@function.inner",
				["]A"] = "@attribute.inner",
				-- ["]C"] = "@call.inner",
			},
			goto_previous_start = {
				["[f"] = "@function.outer",
				["[b"] = "@parameter.outer",
				["[d"] = "@block.inner",
				["[e"] = "@function.inner",
				["[a"] = "@attribute.inner",
				-- ["[c"] = "@call.inner",
			},
			goto_previous_end = {
				["[F"] = "@function.outer",
				["[B"] = "@parameter.outer",
				["[D"] = "@block.inner",
				["[E"] = "@function.inner",
				["[A"] = "@attribute.inner",
				-- ["[C"] = "@call.inner",
			},
		},
		select = {
			enable = true,
			lookahead = true,
			keymaps = {
				["af"] = "@function.outer",
				["if"] = "@function.inner",
				["ac"] = "@call.outer",
				["ic"] = "@call.inner",
				["aC"] = "@class.outer",
				["iC"] = "@class.inner",
				["ib"] = "@parameter.inner",
				["ab"] = "@parameter.outer",
				["iB"] = "@block.inner",
				["aB"] = "@block.outer",
				["id"] = "@block.inner",
				["ad"] = "@block.outer",
				["il"] = "@loop.inner",
				["al"] = "@loop.outer",
				["ia"] = "@attribute.inner",
				["aa"] = "@attribute.outer",
			},
		},
	},
	textsubjects = {
		enable = true,
		prev_selection = ",",
		keymaps = {
			["."] = "textsubjects-smart",
			[";"] = "textsubjects-container-outer",
			["i;"] = "textsubjects-container-inner",
		},
	},
})
